### ISSUE TITLE
No RecSync settings

### ISSUE THREAD

**Issue by l1346792580123** [MobileRoboticsSkoltech/OpenCamera-Sensors#64]
Thanks for sharing this great work! In order to synchronized recording on multiple smartphones, the "Use RecSync" switch needs to be enabled. However, I can not find "RecSync settings" in the preferences page. My perferences page is similar to
![1](https://user-images.githubusercontent.com/25956606/153817413-b949159e-6188-493c-b99c-d92cb0faf39a.png). And there are only 4 buttons when I open this app. The synchronization button is missing. Does this releated to the type of phones?

**Comment by TimPushkin** [comment]
Do you use the apk in Releases or the latest version from `master` branch? The thing is that RecSync is currently in the `master` but has not yet been released as an apk.

I hope an apk will be released soon, but now you can build one by yourself from the `master` branch. And then your preferences should look like this: 
![Untitled-1](https://user-images.githubusercontent.com/71890197/153867998-57dd1b47-9827-4320-9682-99eec9c5bc28.png)

The switch you need is located in "RecSync settings..." and should be available even if your device doesn't support RecSync -- then it will be greyed out.

**Comment by l1346792580123** [comment]
Thanks for your reply. I have downloaded the apk from https://github.com/MobileRoboticsSkoltech/OpenCamera-Sensors/releases/latest/download/app-release.apk. I will try to build the apk by myself.
