### ISSUE TITLE
not fully synchronized recording

### ISSUE THREAD

**Issue by l1346792580123** [MobileRoboticsSkoltech/OpenCamera-Sensors#68]
I am able to perform synchronized recording after using another type phone. While I have found that the recorded videos are not fully synchronized. I have recorded two videos with two phones while the total frames of these two videos are different. One of the videos has a total frame count of 472 and the other has 469. I upload the video to the computer and use cv2 to read the total number of frames. Is this normal ? The two phones are different types. Will the results be more synchronized using two identical phones?

**Comment by TimPushkin** [comment]
The results you got are expected: OpenCamera Sensors mainly synchronizes the recordings by timestamps of frames, however the synchronization of the moments when recordings start and end is not so good (as it is affected by Wi-Fi signal speed). It means that you have to extract the parts when both phones were recording by yourself and you'll get the synchronized videos.

You can cut the videos by hand somehow or make use of script for extraction of synchronized frames found [here](https://github.com/MobileRoboticsSkoltech/RecSync-android) (see "Extraction and matching of the frames" section of README), for example.

**Comment by l1346792580123** [comment]
Thanks for your quick reply, I have found that running the script requires a corresponding [csv file](https://github.com/MobileRoboticsSkoltech/RecSync-android/blob/47fef0734f66bba545c191f31dcdbe6a72c5733b/utils/src/extraction_utils.py#L37) for each video.  How can I get or generate this csv file?

**Comment by TimPushkin** [comment]
OpenCamera Sensors creates one for each video when recording with RecSync enabled. In the folder where OpenCamera writes all the videos there should be a corresponding subfolder for each one. In such subfolder you can find a file named `<video name>_recsync_<leader or client>_<device id>.csv` -- this is the file you need.

**Comment by l1346792580123** [comment]
Thanks for your reply!
