### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by shuvashish76** [MobileRoboticsSkoltech/OpenCamera-Sensors#74]
Currently the app is available on [izzy repo](https://apt.izzysoft.de/fdroid/index/apk/com.opencamera_sensors.app).
Would you consider putting this app on F-Droid, please?

RFP : https://gitlab.com/fdroid/rfp/-/issues/2129

**Comment by TimPushkin** [comment]
Sure. I'll be the one working on it. Not sure for now, how long it'll take, as I have no experience with F-Droid, but I'll see what I can do.
